import { useEffect, useState } from 'react'
import { Download } from 'lucide-react'
import { Workspace } from '../templates/workspace'
import { FormSection, DetailSection } from '../patterns/shared-patterns'
import { Button } from '../components/ui/button'
import { SelectField } from '../components/ui/select-field'
import { DatePicker } from '../components/calendar/date-picker'
import { DataTable, type DataTableColumn } from '../components/data-table/data-table'
import { WorkspaceState } from '../components/feedback/workspace-state'
import { caseStageAging, formatDuration } from '../cases/case-aging'
import type { ApplicationRecord } from '../customers/customer-model'
import { filterCases, emptyReportFilters, caseMetrics, countBy, reportsRepository, type ReportFilters } from './reports'
import { apiReportsRepository } from './api-reports'
import { usePermissionPreview } from './permissions'
import { PermissionActor, PermissionGate } from './ui'
import './operations.css'

export function ReportPage() {
  const preview = usePermissionPreview()
  const apiMode = import.meta.env.MODE !== 'test' && import.meta.env.VITE_AUTH_PROVIDER !== 'mock'
  const [cases, setCases] = useState<ApplicationRecord[]>([])
  const [tasks, setTasks] = useState<{ caseId: string; status: string }[]>([])
  const [finance, setFinance] = useState<{ commissions: { caseId: string; status: string; amount: number }[]; clawbacks: { caseId: string; amount: number }[]; incentives: { amount: number }[] } | null>(null)
  const [filters, setFilters] = useState(emptyReportFilters)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [loadError, setLoadError] = useState('')
  const [reloadKey, setReloadKey] = useState(0)
  useEffect(() => { if (preview.loading) return; if (!preview.actorId || !preview.can('Reports', 'view')) { setLoading(false); return } let live = true; setLoading(true); setError(''); setLoadError(''); void (async () => { try { const repository = apiMode ? apiReportsRepository : reportsRepository; const data = await repository.load(preview.actorId); const financial = preview.can('Reports', 'view-financial') ? await repository.finance(preview.actorId) : null; if (live) { setCases(data.cases); setTasks(data.tasks); setFinance(financial) } } catch (cause) { if (live) setLoadError(cause instanceof Error ? cause.message : 'Could not load Reports.') } finally { if (live) setLoading(false) } })(); return () => { live = false } }, [preview.actorId, preview.permissions, preview.loading, reloadKey, apiMode])
  const filtered = filterCases(cases, filters)
  const filteredIds = new Set(filtered.map(item => item.id))
  const metrics = caseMetrics(filtered)
  const select = (key: keyof ReportFilters, label: string, values: string[], format?: (value: string) => string) => <SelectField label={label} value={filters[key] || 'all'} onValueChange={value => setFilters(current => ({ ...current, [key]: value === 'all' ? '' : value }))} options={[{ value: 'all', label: 'All' }, ...[...new Set(values.filter(Boolean))].sort().map(value => ({ value, label: format?.(value) ?? value }))]} />
  const user = (id: string) => preview.users.find(item => item.id === id)?.fullName ?? id
  const groups = [{ title: 'Cases by Bank', items: countBy(filtered, item => item.bank) }, { title: 'Cases by Product', items: countBy(filtered, item => item.product) }, { title: 'Cases by Product Variant', items: countBy(filtered, item => item.productVariant) }, { title: 'Cases by Stage', items: countBy(filtered, item => item.stage) }]
  const stageGroups = countBy(filtered, item => item.stage).map(group => ({ ...group, overdue: filtered.filter(item => item.stage === group.label && caseStageAging(item)?.status === 'Overdue').length, averageHours: filtered.filter(item => item.stage === group.label && caseStageAging(item)).reduce((sum, item) => sum + (caseStageAging(item)?.elapsedMs ?? 0), 0) / Math.max(1, filtered.filter(item => item.stage === group.label && caseStageAging(item)).length) / 3600000 }))
  const columns: DataTableColumn<ApplicationRecord>[] = [{ id: 'case', header: 'Case', value: item => item.caseNumber }, { id: 'owner', header: 'Case Owner', value: item => user(item.caseOwnerId) }, { id: 'stage', header: 'Stage', value: item => item.stage }, { id: 'aging', header: 'Stage Aging', value: item => caseStageAging(item) ? formatDuration(caseStageAging(item)!.elapsedMs) : '—' }, { id: 'sla', header: 'SLA', value: item => caseStageAging(item)?.status ?? '—' }, { id: 'due', header: 'Due', value: item => caseStageAging(item)?.dueAt ? new Date(caseStageAging(item)!.dueAt).toLocaleString() : '—' }]
  const exportFiltered = async () => { setError(''); try { const csv = apiMode ? await apiReportsRepository.exportCsv(filtered) : await reportsRepository.exportCsv(filtered, preview.actorId); const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' })); const link = document.createElement('a'); link.href = url; link.download = 'amafh-cases-report.csv'; link.click(); URL.revokeObjectURL(url) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not export report.') } }
  return <Workspace title="Reporting & Analytics" description={apiMode ? 'Operational reports from current Case, Task and Finance records.' : 'Operational reports from local Case, Task and Finance records.'}><PermissionActor preview={preview} /><PermissionGate preview={preview} domain="Reports" action="view">{error && <p role="alert" className="amafh-case-error">{error}</p>}{loading ? <WorkspaceState kind="loading" title="Loading Reports" /> : loadError ? <WorkspaceState kind="error" title="Could not load Reports" description={loadError} action={<Button onClick={() => setReloadKey(value => value + 1)}>Try again</Button>} /> : <div className="amafh-ops-grid">
    <FormSection title="Shared filters"><div className="amafh-ops-fields"><DatePicker label="From" value={filters.from} onValueChange={from => setFilters(current => ({ ...current, from }))} /><DatePicker label="Until" value={filters.until} onValueChange={until => setFilters(current => ({ ...current, until }))} />{select('bank', 'Bank', cases.map(item => item.bank))}{select('product', 'Product', cases.map(item => item.product))}{select('variant', 'Product Variant', cases.map(item => item.productVariant))}{select('owner', 'Case Owner', cases.map(item => item.caseOwnerId), user)}{select('coordinator', 'Coordinator', cases.map(item => item.coordinatorId), user)}{select('status', 'Case Status', cases.map(item => item.status))}{select('stage', 'Stage', cases.map(item => item.stage))}</div><div className="amafh-ops-actions"><Button variant="secondary" onClick={() => setFilters(emptyReportFilters())}>Clear filters</Button>{preview.can('Reports', 'export') && <Button icon={<Download size={16} strokeWidth={1.75} aria-hidden="true" />} onClick={() => { void exportFiltered() }}>Export filtered CSV</Button>}</div></FormSection>
    <DetailSection title="Case summary" items={Object.entries(metrics).map(([label, value]) => ({ label: label.replace(/([A-Z])/g, ' $1').replace(/^./, c => c.toUpperCase()), value: String(value) }))} />
    {filtered.length ? <><div className="amafh-ops-fields">{groups.map(group => <DetailSection key={group.title} title={group.title} items={group.items.map(item => ({ label: item.label, value: String(item.count) }))} />)}</div><FormSection title="Stage SLA and bottlenecks"><div className="amafh-ops-list">{stageGroups.map(item => <p key={item.label}><strong>{item.label}</strong> · {item.count} Cases · {item.overdue} overdue · {item.averageHours.toFixed(1)}h average current-stage aging</p>)}</div></FormSection><DataTable tableId="report-overdue" caption="Filtered Cases and stage aging" rows={filtered} columns={columns} rowId={item => item.id} pageSize={10} /></> : <WorkspaceState kind="empty" title="No Cases match these filters" />}
    {preview.can('Reports', 'view-performance') && <><div className="amafh-ops-fields"><DetailSection title="Case Owner workload" items={countBy(filtered, item => item.caseOwnerId).map(item => ({ label: user(item.label), value: `${item.count} Cases · ${filtered.filter(record => record.caseOwnerId === item.label && record.stage === 'Final Outcome').length} completed` }))} /><DetailSection title="Coordinator workload" items={countBy(filtered, item => item.coordinatorId).map(item => ({ label: item.label === 'Unassigned' ? 'Unassigned' : user(item.label), value: `${item.count} Cases · ${filtered.filter(record => record.coordinatorId === item.label && record.stage === 'Final Outcome').length} completed` }))} /></div><DetailSection title="Tasks linked to filtered Cases" items={[{ label: 'Total', value: String(tasks.filter(item => item.caseId && filteredIds.has(item.caseId)).length) }, { label: 'Open or In Progress', value: String(tasks.filter(item => item.caseId && filteredIds.has(item.caseId) && ['Open', 'In Progress'].includes(item.status)).length) }]} /></>}
    {finance && preview.can('Reports', 'view-financial') && <DetailSection title="Finance for filtered Cases" items={[{ label: 'Calculated', value: finance.commissions.filter(item => filteredIds.has(item.caseId) && item.status === 'Calculated').reduce((sum, item) => sum + item.amount, 0).toFixed(2) }, { label: 'Pending', value: finance.commissions.filter(item => filteredIds.has(item.caseId) && item.status === 'Pending').reduce((sum, item) => sum + item.amount, 0).toFixed(2) }, { label: 'Approved', value: finance.commissions.filter(item => filteredIds.has(item.caseId) && item.status === 'Approved').reduce((sum, item) => sum + item.amount, 0).toFixed(2) }, { label: 'Paid', value: finance.commissions.filter(item => filteredIds.has(item.caseId) && item.status === 'Paid').reduce((sum, item) => sum + item.amount, 0).toFixed(2) }, { label: 'Clawback', value: finance.clawbacks.filter(item => filteredIds.has(item.caseId)).reduce((sum, item) => sum + item.amount, 0).toFixed(2) }, { label: 'Incentives (all periods)', value: finance.incentives.reduce((sum, item) => sum + item.amount, 0).toFixed(2) }]} />}
  </div>}</PermissionGate></Workspace>
}
