import { expect, test } from '@playwright/test'
import { signIn } from './helpers/auth'

test('protected deep link returns after login, survives reload, and logout removes access', async ({ page }) => {
  await page.goto('/templates/detail')
  await expect(page).toHaveURL(/\/login\?returnTo=%2Ftemplates%2Fdetail$/)
  await expect(page.getByRole('heading', { name: 'Sign in' })).toBeVisible()
  await expect(page.getByRole('navigation', { name: 'Primary navigation' })).toHaveCount(0)
  await page.getByRole('textbox', { name: 'Email' }).fill('demo.user@example.test')
  await page.getByLabel('Password').fill('local-preview')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page).toHaveURL(/\/templates\/detail$/)
  await expect(page.getByRole('heading', { name: 'Record detail' })).toBeVisible()
  await expect(page.getByText('Demo User')).toBeVisible()
  const stored = await page.evaluate(() => localStorage.getItem('amafh-v2.mock-session.v1'))
  expect(stored).toContain('demo.user@example.test')
  expect(stored).not.toContain('local-preview')
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Record detail' })).toBeVisible()
  await page.getByRole('button', { name: 'Log out' }).click()
  await expect(page.getByRole('heading', { name: 'Sign in' })).toBeVisible()
  expect(await page.evaluate(() => localStorage.getItem('amafh-v2.mock-session.v1'))).toBeNull()
  await page.goto('/templates/list')
  await expect(page).toHaveURL(/\/login\?returnTo=%2Ftemplates%2Flist$/)
})

test('invalid local session is ignored and external return path is rejected', async ({ page }) => {
  await page.goto('/login?returnTo=https%3A%2F%2Fexample.com')
  await page.evaluate(() => localStorage.setItem('amafh-v2.mock-session.v1', '{broken'))
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Sign in' })).toBeVisible()
  expect(await page.evaluate(() => localStorage.getItem('amafh-v2.mock-session.v1'))).toBeNull()
  await page.getByRole('textbox', { name: 'Email' }).fill('demo@example.test')
  await page.getByLabel('Password').fill('preview')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page).toHaveURL(/\/templates\/dashboard$/)
  await page.goto('/login')
  await expect(page).toHaveURL(/\/templates\/dashboard$/)
})

test('login and user controls fit a mobile viewport', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/templates/form')
  await expect(page.getByRole('heading', { name: 'Sign in' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(391)
  await signIn(page)
  await page.goto('/templates/form')
  await expect(page.getByRole('heading', { name: 'Form' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(391)
})
