import { expect, test } from '@playwright/test'

test.skip(process.env.PLAYWRIGHT_AUTH_API !== '1', 'Requires the isolated API authentication test database')

for (const width of [1440, 390]) test(`database session login, restore and logout at ${width}px`, async ({ page, context }) => {
  await page.setViewportSize({ width, height: 900 })
  await page.goto('/login')
  await expect(page.getByRole('heading', { name: 'Sign in' })).toBeVisible()
  await page.getByRole('textbox', { name: 'Email' }).fill('owner-auth-check@example.test')
  await page.getByLabel('Password').fill('wrong')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page.getByRole('alert')).toContainText('Invalid email or password')
  await page.getByLabel('Password').fill('owner changed secret')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page.getByRole('button', { name: 'Log out' })).toBeVisible()
  const cookies = await context.cookies()
  expect(cookies.find(cookie => cookie.name === 'amafh_session')?.httpOnly).toBe(true)
  expect(await page.evaluate(() => localStorage.getItem('amafh-v2.mock-session.v1'))).toBeNull()
  await page.reload()
  await expect(page.getByRole('button', { name: 'Log out' })).toBeVisible()
  await page.getByRole('button', { name: 'Account security' }).click()
  await expect(page).toHaveURL(/\/account\/security$/)
  await expect(page.getByRole('heading', { level: 1, name: 'Account security' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1)).toBe(false)
  await page.getByRole('button', { name: 'Log out', exact: true }).click()
  await expect(page).toHaveURL(/\/login/)
  await expect(page.getByRole('heading', { name: 'Sign in' })).toBeVisible()
  expect(await page.evaluate(async () => (await fetch('/api/v1/auth/session')).status)).toBe(401)
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1)).toBe(false)
})

test('setup link rejects an invalid token in the browser', async ({ page }) => {
  await page.goto('/set-password?token=invalid')
  await expect(page.getByRole('heading', { name: 'Set password' })).toBeVisible()
  await page.getByRole('textbox', { name: 'New password' }).fill('a sufficiently long password')
  await page.getByRole('textbox', { name: 'Confirm password' }).fill('a sufficiently long password')
  await page.getByRole('button', { name: 'Save password' }).click()
  await expect(page.getByRole('alert')).toContainText('invalid, expired, or already used')
})

test('owner generates a one-time setup link from a user detail and the user sets a password', async ({ page }) => {
  await page.goto('/login')
  await page.getByRole('textbox', { name: 'Email' }).fill('owner-auth-check@example.test')
  await page.getByLabel('Password').fill('owner changed secret')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page.getByRole('button', { name: 'Log out', exact: true })).toBeVisible()
  await page.evaluate(() => {
    localStorage.setItem('amafh-v2.mock-users.v1', JSON.stringify({ version: 1, users: [{ id: 'sample-aisha', fullName: 'Auth Check New User', email: 'new-user-auth-check@example.test', userType: 'User Type A', reportingManagerId: '', organization: 'Organization A', organizationScope: 'organization', officeBranch: '', department: '', team: '', status: 'active' }] }))
    localStorage.setItem('amafh-v2.mock-permissions.v1', JSON.stringify({ version: 1, permissions: ['view', 'edit'].map(action => ({ id: `users-${action}`, domain: 'Users', action, description: 'Browser test permission.', enabled: true, userTypeIds: ['sample-type-1'], createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() })) }))
    sessionStorage.setItem('amafh-v2.case-preview-actor', 'sample-aisha')
  })
  await page.goto('/administration/users/sample-aisha')
  await expect(page.getByRole('heading', { name: 'User detail' })).toBeVisible()
  await page.getByRole('button', { name: 'Generate setup link' }).click()
  const link = await page.getByRole('textbox', { name: 'One-time setup link' }).inputValue()
  expect(link).toContain('/set-password?token=')
  await page.getByRole('button', { name: 'Log out', exact: true }).click()
  await page.goto(link)
  await page.getByRole('textbox', { name: 'New password' }).fill('newly chosen user password')
  await page.getByRole('textbox', { name: 'Confirm password' }).fill('newly chosen user password')
  await page.getByRole('button', { name: 'Save password' }).click()
  await expect(page.getByText('Your password is ready.')).toBeVisible()
  await page.getByRole('button', { name: 'Sign in' }).click()
  await page.getByRole('textbox', { name: 'Email' }).fill('new-user-auth-check@example.test')
  await page.getByLabel('Password').fill('newly chosen user password')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page.getByRole('button', { name: 'Log out', exact: true })).toBeVisible()
  await page.goto(link)
  await page.getByRole('textbox', { name: 'New password' }).fill('another secure user password')
  await page.getByRole('textbox', { name: 'Confirm password' }).fill('another secure user password')
  await page.getByRole('button', { name: 'Save password' }).click()
  await expect(page.getByRole('alert')).toContainText('invalid, expired, or already used')
})
