import { expect, test, type Page } from '@playwright/test'
import { signIn } from './helpers/auth'

const actions = ['view', 'create', 'edit', 'delete', 'assign-owner', 'approve', 'reject', 'assign-coordinator', 'submit-to-bank', 'add-bank-file-number', 'update-stage', 'view-history', 'edit-history', 'lock', 'add-stage', 'edit-stage', 'delete-stage', 'reorder-stage', 'activate-stage', 'set-stage-duration']
async function grantCases(page: Page) {
  await page.evaluate(actions => localStorage.setItem('amafh-v2.mock-permissions.v1', JSON.stringify({ version: 1, permissions: [...actions.map(action => ({ id: `case-${action}`, domain: 'Cases', action, description: `${action} cases.`, enabled: true, userTypeIds: ['sample-type-1'], createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() })), { id: 'customer-view', domain: 'Customers', action: 'view', description: 'View customers.', enabled: true, userTypeIds: ['sample-type-1'], createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }] })), actions)
}
async function choose(page: Page, label: string, option: string) { await page.getByRole('combobox', { name: label, exact: true }).click(); await page.getByRole('option', { name: option, exact: true }).click() }
async function noOverflow(page: Page) { expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1)).toBe(false) }

for (const width of [1440, 1024, 390]) {
  test(`Case list, permission actions, lock and history at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 }); await signIn(page); await page.evaluate(() => { localStorage.setItem('amafh-v2.mock-permissions.v1', JSON.stringify({ version: 1, permissions: [{ id: 'case-view', domain: 'Cases', action: 'view', description: 'View cases.', enabled: true, userTypeIds: ['sample-type-1'], createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }] })); sessionStorage.setItem('amafh-v2.case-preview-actor', 'sample-aisha') }); await page.goto('/cases')
    await expect(page.getByRole('heading', { level: 1, name: 'Cases' })).toBeVisible()
    await expect(page.getByRole('navigation', { name: 'Breadcrumb' }).getByText('Cases')).toBeVisible()
    if (width === 390) {
      await page.getByRole('button', { name: 'Open navigation' }).click()
      await expect(page.getByRole('navigation', { name: 'Primary navigation' }).getByRole('button', { name: 'Cases' })).toBeVisible()
      await page.getByRole('button', { name: 'Close navigation' }).first().click()
    }
    const table = page.getByRole('table', { name: 'Cases' })
    await expect(table).toBeVisible(); await expect(table.getByRole('row', { name: /CASE-0001/ })).toBeVisible(); await noOverflow(page)
    await page.getByRole('searchbox', { name: 'Search' }).fill('not here'); await expect(page.getByText('No results')).toBeVisible()
    await page.getByRole('searchbox', { name: 'Search' }).fill(''); await choose(page, 'Status', 'Pending SM Approval'); await expect(table.getByRole('row', { name: /CASE-0001/ })).toBeVisible()
    await table.getByRole('row', { name: /CASE-0001/ }).getByRole('button', { name: 'View' }).click()
    await expect(page.getByRole('heading', { name: 'Case workspace' })).toBeVisible()
    await expect(page.getByText('Pending SM Approval').first()).toBeVisible()
    await expect(page.getByRole('button', { name: 'Approve' })).toHaveCount(0)
    await grantCases(page); await page.reload(); await choose(page, 'Acting user (local permission preview)', 'Aisha Rahman · User Type A')
    await expect(page.getByRole('button', { name: 'Approve' })).toBeVisible()
    await page.getByRole('button', { name: 'Approve' }).click()
    await expect(page.getByText('SM Approved').first()).toBeVisible()
    await expect(page.getByText('Unlocked')).toBeVisible()
    await choose(page, 'Case Coordinator', 'Sara Ali'); await page.getByRole('button', { name: 'Assign Case Coordinator' }).click()
    await expect(page.getByRole('button', { name: 'Submit to Bank' })).toHaveCount(0)
    await choose(page, 'Acting user (local permission preview)', 'Sara Ali · User Type A')
    await page.getByRole('button', { name: 'Submit to Bank' }).click()
    await page.getByRole('textbox', { name: 'Bank File Number' }).fill('BN-CASE-001')
    await page.getByRole('button', { name: 'Add Bank File Number' }).click()
    await expect(page.getByText('Locked · original submission protected')).toBeVisible()
    await expect(page.getByRole('button', { name: 'Edit Application' })).toHaveCount(0)
    await choose(page, 'Next Case Stage', 'Stage 1'); await page.getByRole('button', { name: 'Update Stage' }).click()
    await page.getByRole('button', { name: 'View History' }).click()
    const timeline = page.getByRole('heading', { name: 'Case History' }).locator('..')
    await expect(timeline).toContainText('Case Created'); await expect(timeline).toContainText('SM Approved'); await expect(timeline).toContainText('Case Locked'); await expect(timeline).toContainText('Stage 1')
    await noOverflow(page); await page.reload(); await expect(page.getByText('Locked · original submission protected')).toBeVisible()
  })
}

test('Case rejection, protected deletion, empty and recoverable error states', async ({ page }) => {
  await signIn(page); await grantCases(page); await page.goto('/cases/sample-case-2')
  await choose(page, 'Acting user (local permission preview)', 'Aisha Rahman · User Type A')
  await page.getByRole('button', { name: 'Reject' }).click()
  await expect(page.getByText('SM Rejected').first()).toBeVisible()
  await expect(page.getByRole('button', { name: 'Approve' })).toHaveCount(0)
  await page.goto('/cases/sample-case-3'); await page.getByRole('button', { name: 'Delete Case' }).click()
  await expect(page.getByRole('dialog', { name: 'Delete Case' })).toBeVisible()
  await page.getByRole('dialog', { name: 'Delete Case' }).getByRole('button', { name: 'Delete', exact: true }).click()
  await expect(page).toHaveURL(/\/cases$/)
  await page.evaluate(() => localStorage.setItem('amafh-v2.mock-customer-management.v1', JSON.stringify({ version: 1, customers: [], applications: [] })))
  await page.reload(); await expect(page.getByText('Nothing here yet')).toBeVisible()
  await page.evaluate(() => localStorage.setItem('amafh-v2.mock-customer-management.v1', '{broken'))
  await page.reload(); await expect(page.getByText('Could not load records')).toBeVisible()
})

test('Create Application uses dependent catalogue selections and opens the linked Case', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 900 }); await signIn(page); await grantCases(page); await page.goto('/applications/new')
  await expect(page.getByRole('combobox', { name: 'Product', exact: true })).toBeDisabled()
  await expect(page.getByRole('combobox', { name: 'Product Variant' })).toBeDisabled()
  await page.getByRole('searchbox', { name: 'Search existing customers' }).fill('P0000001')
  await page.getByRole('button', { name: 'Use existing customer' }).click()
  await choose(page, 'Bank', 'Sample Bank')
  await expect(page.getByRole('combobox', { name: 'Product', exact: true })).toBeEnabled()
  await choose(page, 'Product', 'Sample Product'); await choose(page, 'Product Variant', 'Sample Variant')
  await page.getByRole('spinbutton', { name: 'Requested Amount' }).fill('82000')
  await choose(page, 'Case Owner', 'Sara Ali')
  await choose(page, 'Acting user (local permission preview)', 'Aisha Rahman · User Type A')
  await noOverflow(page)
  await page.getByRole('button', { name: 'Create Application' }).click()
  await expect(page).toHaveURL(/\/customers\/sample-individual-1$/)
  await page.getByRole('button', { name: 'Open Case' }).last().click()
  await expect(page.getByRole('heading', { name: 'Case workspace' })).toBeVisible()
  await expect(page.getByText('Pending SM Approval').first()).toBeVisible()
  await expect(page.getByText('Sara Ali').first()).toBeVisible()
  await noOverflow(page)
})

test('direct Create Application route requires an assigned Case Create permission', async ({ page }) => {
  await signIn(page); await page.goto('/applications/new')
  await choose(page, 'Acting user (local permission preview)', 'Aisha Rahman · User Type A')
  await expect(page.getByRole('button', { name: 'Create Application' })).toBeDisabled()
  await grantCases(page); await page.reload()
  await expect(page.getByRole('button', { name: 'Create Application' })).toBeEnabled()
})

for (const width of [1440, 1024, 390]) {
  test(`Product Stage administration CRUD, order, state and permissions at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 }); await signIn(page)
    await page.goto('/administration/banks-products/products/sample-product-1')
    await page.getByRole('button', { name: 'Product Stages' }).click()
    await expect(page).toHaveURL(/\/products\/sample-product-1\/stages$/)
    await choose(page, 'Acting user (local permission preview)', 'Aisha Rahman · User Type A')
    await expect(page.getByRole('button', { name: 'Add Stage' })).toHaveCount(0)
    await grantCases(page); await page.reload()
    await expect(page.getByRole('heading', { name: 'Sample Product · Product Stages' })).toBeVisible()
    await page.getByRole('textbox', { name: 'Stage Name' }).fill('Follow Up')
    await page.getByRole('spinbutton', { name: 'Expected Duration (hours)' }).fill('2')
    await page.getByRole('button', { name: 'Add Stage' }).click()
    const stage = page.getByRole('listitem').filter({ hasText: 'Follow Up' })
    await expect(stage).toContainText('Expected Duration: 2 hours')
    await stage.getByRole('button', { name: 'Move up' }).click()
    await expect(stage).toContainText('4. Follow Up')
    await stage.getByRole('button', { name: 'Edit Stage' }).click()
    await page.getByRole('textbox', { name: 'Stage Name' }).fill('Follow Up Review')
    await page.getByRole('spinbutton', { name: 'Expected Duration (hours)' }).fill('3')
    await choose(page, 'Stage State', 'Inactive')
    await page.getByRole('button', { name: 'Save Stage' }).click()
    const updated = page.getByRole('listitem').filter({ hasText: 'Follow Up Review' })
    await expect(updated).toContainText('Inactive'); await expect(updated).toContainText('3 hours')
    await updated.getByRole('button', { name: 'Delete Stage' }).click()
    await page.getByRole('dialog', { name: 'Delete Product Stage' }).getByRole('button', { name: 'Delete', exact: true }).click()
    await expect(page.getByText('Follow Up Review')).toHaveCount(0)
    await noOverflow(page)
  })
}

test('used Product Stage blocks identity changes and preserves Case SLA snapshot and history', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 900 }); await signIn(page); await grantCases(page); await page.goto('/cases/sample-case-1')
  await choose(page, 'Acting user (local permission preview)', 'Aisha Rahman · User Type A')
  await page.getByRole('button', { name: 'Approve' }).click()
  await choose(page, 'Case Coordinator', 'Sara Ali'); await page.getByRole('button', { name: 'Assign Case Coordinator' }).click()
  await choose(page, 'Acting user (local permission preview)', 'Sara Ali · User Type A')
  await page.getByRole('button', { name: 'Submit to Bank' }).click()
  await page.getByRole('textbox', { name: 'Bank File Number' }).fill('BF-SLA')
  await page.getByRole('button', { name: 'Add Bank File Number' }).click()
  await page.evaluate(() => { const permissions = JSON.parse(localStorage.getItem('amafh-v2.mock-permissions.v1')!); permissions.permissions.find((item: { action: string }) => item.action === 'update-stage').enabled = false; localStorage.setItem('amafh-v2.mock-permissions.v1', JSON.stringify(permissions)) })
  await page.reload()
  await expect(page.getByRole('button', { name: 'Update Stage' })).toHaveCount(0)
  await grantCases(page); await page.reload()
  await choose(page, 'Next Case Stage', 'Stage 1'); await page.getByRole('button', { name: 'Update Stage' }).click()
  await expect(page.getByText('24 hours · captured at stage entry')).toBeVisible()
  const original = await page.evaluate(() => { const store = JSON.parse(localStorage.getItem('amafh-v2.mock-customer-management.v1')!); const item = store.applications.find((item: { id: string }) => item.id === 'sample-case-1'); return { started: item.stageStartedAt, history: JSON.stringify(item.history) } })
  await page.goto('/administration/banks-products/products/sample-product-1/stages')
  const usedStage = page.getByRole('listitem').filter({ hasText: '1. Stage 1' })
  await expect(usedStage).toContainText('Used by Case')
  await expect(usedStage.getByRole('button', { name: 'Delete Stage' })).toBeDisabled()
  await expect(usedStage.getByRole('button', { name: 'Move down' })).toBeDisabled()
  await usedStage.getByRole('button', { name: 'Edit Stage' }).click()
  await expect(page.getByRole('textbox', { name: 'Stage Name' })).toBeDisabled()
  await expect(page.getByRole('combobox', { name: 'Stage State' })).toBeDisabled()
  await page.getByRole('spinbutton', { name: 'Expected Duration (hours)' }).fill('1')
  await page.getByRole('button', { name: 'Save Stage' }).click()
  await page.goto('/cases/sample-case-1')
  await expect(page.getByText('24 hours · captured at stage entry')).toBeVisible()
  expect(await page.evaluate(() => { const store = JSON.parse(localStorage.getItem('amafh-v2.mock-customer-management.v1')!); const item = store.applications.find((item: { id: string }) => item.id === 'sample-case-1'); return { started: item.stageStartedAt, history: JSON.stringify(item.history) } })).toEqual(original)
  await page.evaluate(() => { const store = JSON.parse(localStorage.getItem('amafh-v2.mock-customer-management.v1')!); store.applications.find((item: { id: string }) => item.id === 'sample-case-1').stageStartedAt = new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(); localStorage.setItem('amafh-v2.mock-customer-management.v1', JSON.stringify(store)) })
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Current Stage SLA' })).toBeVisible()
  await expect(page.getByText('Overdue', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('24 hours · captured at stage entry')).toBeVisible()
  await page.goto('/cases')
  await expect(page.getByRole('row', { name: /CASE-0001/ })).toContainText('Overdue')
  await noOverflow(page)
})
