import { expect, test, type Page } from '@playwright/test'
import { signIn } from './helpers/auth'

async function signInForCaseCreation(page: Page) {
  await signIn(page)
  await page.evaluate(() => sessionStorage.setItem('amafh-v2.case-preview-actor', 'sample-aisha'))
  await page.evaluate(() => localStorage.setItem('amafh-v2.mock-permissions.v1', JSON.stringify({ version: 1, permissions: [{ id: 'case-create', domain: 'Cases', action: 'create', description: 'Create cases.', enabled: true, userTypeIds: ['sample-type-1'], createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }, ...['view', 'edit', 'delete'].map(action => ({ id: `customer-${action}`, domain: 'Customers', action, description: `${action} customers.`, enabled: true, userTypeIds: ['sample-type-1'], createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }))] })))
}

async function choose(page: Page, field: string, option: string) { await page.getByRole('combobox', { name: field, exact: true }).click(); await page.getByRole('option', { name: option, exact: true }).click() }
async function fillApplication(page: Page) { await choose(page, 'Bank', 'Sample Bank'); await choose(page, 'Product', 'Sample Product'); await choose(page, 'Product Variant', 'Sample Variant'); await page.getByRole('spinbutton', { name: 'Requested Amount' }).fill('75000'); await choose(page, 'Case Owner', 'Aisha Rahman'); await choose(page, 'Acting user (local permission preview)', 'Aisha Rahman · User Type A') }
async function noOverflow(page: Page) { expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1)).toBe(false) }

for (const width of [1440, 1024, 390]) {
  test(`customer list, detail, search and filters at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 }); await signInForCaseCreation(page); await page.goto('/customers')
    const table = page.getByRole('table', { name: 'Customers' })
    await expect(table).toBeVisible(); await expect(page.getByRole('button', { name: 'Create Customer' })).toHaveCount(0); await noOverflow(page)
    await page.getByRole('searchbox', { name: 'Search' }).fill('Aisha')
    await expect(table.getByRole('row', { name: /Aisha Rahman/ })).toBeVisible()
    await page.getByRole('searchbox', { name: 'Search' }).fill('no customer')
    await expect(page.getByText('No results')).toBeVisible()
    await page.getByRole('searchbox', { name: 'Search' }).fill('')
    await page.getByRole('combobox', { name: 'Customer Type' }).selectOption('company')
    await expect(table.getByRole('row', { name: /Gulf Sample Trading LLC/ })).toBeVisible()
    await expect(table.getByRole('row', { name: /Aisha Rahman/ })).toHaveCount(0)
    await page.getByRole('combobox', { name: 'Customer Type' }).selectOption('all')
    await page.getByRole('combobox', { name: 'Status' }).selectOption('inactive')
    await expect(table.getByRole('row', { name: /Omar Hassan/ })).toBeVisible()
    await page.getByRole('combobox', { name: 'Status' }).selectOption('all')
    await table.getByRole('row', { name: /Aisha Rahman/ }).getByRole('button', { name: 'View' }).click()
    await choose(page, 'Acting user (local permission preview)', 'Aisha Rahman · User Type A')
    await expect(page.getByRole('heading', { level: 1, name: 'Customer detail' })).toBeVisible()
    await expect(page.getByText('sample-case-1')).toBeVisible()
    await expect(page.getByText('sample-case-2')).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Customer history' })).toBeVisible()
    await noOverflow(page)
    await page.getByRole('button', { name: 'Delete Customer' }).click()
    const dialog = page.getByRole('dialog', { name: 'Delete Customer' })
    await expect(dialog).toContainText('2 related Applications/Cases depend')
    await expect(dialog.getByRole('button', { name: 'Delete', exact: true })).toBeDisabled()
  })

  test(`existing Individual matching and Application attachment at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 }); await signInForCaseCreation(page); await page.goto('/customers')
    await page.getByRole('button', { name: 'Create Application' }).click()
    await expect(page.getByRole('heading', { level: 1, name: 'Create Application' })).toBeVisible()
    await page.getByRole('searchbox', { name: 'Search existing customers' }).fill('784-1990-0000000-1')
    const matches = page.getByRole('region', { name: 'Matching customers' })
    await expect(matches).toContainText('Aisha Rahman')
    await matches.getByRole('button', { name: 'Use existing customer' }).click()
    await expect(page.getByText('Selected customer: Aisha Rahman')).toBeVisible()
    await fillApplication(page); await noOverflow(page)
    await page.getByRole('button', { name: 'Create Application' }).click()
    await expect(page).toHaveURL(/\/customers\/sample-individual-1$/)
    await expect(page.getByText('3 linked Applications/Cases')).toBeVisible()
    await page.reload(); await expect(page.getByText('3 linked Applications/Cases')).toBeVisible()
    await page.goto('/customers'); await expect(page.getByRole('table', { name: 'Customers' }).getByRole('row', { name: /Aisha Rahman/ })).toContainText('3')
  })

  test(`new Individual validation, duplicate identity, edit and deactivation at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 }); await signInForCaseCreation(page); await page.goto('/applications/new')
    await fillApplication(page)
    await page.getByRole('textbox', { name: 'Full Name' }).fill('Aisha Rahman')
    await page.getByRole('textbox', { name: 'Mobile' }).fill('0500000001')
    await page.getByRole('textbox', { name: 'Emirates ID' }).fill('784-1990-0000000-1')
    await page.getByRole('button', { name: 'Create Application' }).click()
    await expect(page.getByText('Emirates ID is already assigned to another Individual customer.')).toBeVisible()
    await page.getByRole('textbox', { name: 'Emirates ID' }).fill('784-2001-0000000-9')
    await page.getByRole('textbox', { name: 'Passport Number' }).fill('P0000001')
    await page.getByRole('button', { name: 'Create Application' }).click()
    await expect(page.getByText('Passport Number is already assigned to another Individual customer.')).toBeVisible()
    await page.getByRole('textbox', { name: 'Passport Number' }).fill('P9000009')
    await page.getByRole('button', { name: 'Create Application' }).click()
    await expect(page.getByRole('heading', { level: 1, name: 'Customer detail' })).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Aisha Rahman', exact: true })).toBeVisible()
    await expect(page.getByText('1 linked Application/Case')).toBeVisible()
    await noOverflow(page)
    await page.getByRole('button', { name: 'Edit Customer' }).click()
    await expect(page.getByRole('textbox', { name: 'Emirates ID' })).toHaveValue('784-2001-0000000-9')
    await page.getByRole('button', { name: 'Save changes' }).click()
    await expect(page.getByRole('heading', { level: 1, name: 'Customer detail' })).toBeVisible()
    await page.getByRole('button', { name: 'Edit Customer' }).click()
    await page.getByRole('textbox', { name: 'Passport Number' }).fill('P0000002')
    await page.getByRole('button', { name: 'Save changes' }).click()
    await expect(page.getByText('Passport Number is already assigned to another Individual customer.')).toBeVisible()
    await page.getByRole('textbox', { name: 'Passport Number' }).fill('P9000009')
    await choose(page, 'Status', 'Inactive')
    await page.getByRole('button', { name: 'Save changes' }).click()
    const dialog = page.getByRole('dialog', { name: 'Deactivate Customer' })
    await expect(dialog).toBeVisible()
    await dialog.getByRole('button', { name: 'Deactivate' }).click()
    await expect(page.getByRole('heading', { level: 1, name: 'Customer detail' })).toBeVisible()
    await expect(page.getByText('Status changed to inactive')).toBeVisible()
    await page.reload(); await expect(page.getByText('Status changed to inactive')).toBeVisible()
  })

  test(`Company matching and new Company creation at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 }); await signInForCaseCreation(page); await page.goto('/applications/new')
    await choose(page, 'Customer Type', 'Company / Business')
    await page.getByRole('searchbox', { name: 'Search existing customers' }).fill('TL-00001')
    await expect(page.getByRole('region', { name: 'Matching customers' })).toContainText('Gulf Sample Trading LLC')
    await page.getByRole('button', { name: 'Use existing customer' }).click()
    await fillApplication(page); await page.getByRole('button', { name: 'Create Application' }).click()
    await expect(page).toHaveURL(/\/customers\/sample-company-1$/)
    await expect(page.getByText('2 linked Applications/Cases')).toBeVisible()
    await page.goto('/applications/new'); await choose(page, 'Customer Type', 'Company / Business')
    await fillApplication(page)
    await page.getByRole('textbox', { name: 'Company Name' }).fill('New Sample Business LLC')
    await page.getByRole('textbox', { name: 'Contact Person' }).fill('Sample Contact')
    await page.getByRole('textbox', { name: 'Trade License' }).fill('TL-90001')
    await page.getByRole('textbox', { name: 'Mobile' }).fill('0500000003')
    await page.getByRole('button', { name: 'Create Application' }).click()
    await expect(page.getByRole('heading', { name: 'New Sample Business LLC', exact: true })).toBeVisible()
    await expect(page.getByText('1 linked Application/Case')).toBeVisible()
    await noOverflow(page)
    await page.reload(); await expect(page.getByRole('heading', { name: 'New Sample Business LLC', exact: true })).toBeVisible()
  })
}

test('Customer empty, no-results, recoverable error and allowed deletion', async ({ page }) => {
  await signInForCaseCreation(page); await page.goto('/customers/sample-individual-2')
  await choose(page, 'Acting user (local permission preview)', 'Aisha Rahman · User Type A')
  await page.getByRole('button', { name: 'Delete Customer' }).click()
  const dialog = page.getByRole('dialog', { name: 'Delete Customer' })
  await dialog.getByRole('button', { name: 'Cancel' }).click()
  await page.getByRole('button', { name: 'Delete Customer' }).click()
  await dialog.getByRole('button', { name: 'Delete', exact: true }).click()
  await expect(page).toHaveURL(/\/customers$/)
  await page.reload(); await page.getByRole('searchbox', { name: 'Search' }).fill('Omar Hassan'); await expect(page.getByText('No results')).toBeVisible()
  await page.evaluate(() => localStorage.setItem('amafh-v2.mock-customer-management.v1', JSON.stringify({ version: 1, customers: [], applications: [] })))
  await page.reload(); await expect(page.getByText('Nothing here yet')).toBeVisible()
  await page.evaluate(() => localStorage.setItem('amafh-v2.mock-customer-management.v1', '{broken'))
  await page.reload(); await expect(page.getByText('Could not load records')).toBeVisible()
  await page.evaluate(() => localStorage.setItem('amafh-v2.mock-customer-management.v1', JSON.stringify({ version: 1, customers: [], applications: [] })))
  await page.getByRole('button', { name: 'Try again' }).click(); await expect(page.getByText('Nothing here yet')).toBeVisible()
})

test('Passport matching attaches an existing Individual and Trade License matching prevents a duplicate Company', async ({ page }) => {
  await signInForCaseCreation(page); await page.goto('/applications/new')
  await page.getByRole('searchbox', { name: 'Search existing customers' }).fill('P0000001')
  await expect(page.getByRole('region', { name: 'Matching customers' })).toContainText('Aisha Rahman')
  await page.getByRole('button', { name: 'Use existing customer' }).click()
  await fillApplication(page); await page.getByRole('button', { name: 'Create Application' }).click()
  await expect(page).toHaveURL(/\/customers\/sample-individual-1$/)
  await page.goto('/applications/new'); await choose(page, 'Customer Type', 'Company / Business')
  await fillApplication(page)
  await page.getByRole('textbox', { name: 'Company Name' }).fill('Another Business')
  await page.getByRole('textbox', { name: 'Trade License' }).fill('TL-00001')
  await page.getByRole('button', { name: 'Create Application' }).click()
  await expect(page.getByText('A matching customer already exists. Select the existing customer.')).toBeVisible()
  await expect(page).toHaveURL(/\/applications\/new$/)
})

test('Customer routes are protected and no standalone Create Customer exists', async ({ page }) => {
  await page.goto('/applications/new')
  await expect(page).toHaveURL(/\/login\?returnTo=%2Fapplications%2Fnew$/)
  await page.getByRole('textbox', { name: 'Email' }).fill('preview@example.test')
  await page.getByLabel('Password').fill('preview')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page).toHaveURL(/\/applications\/new$/)
  await page.goto('/customers/new')
  await expect(page).toHaveURL(/\/templates\/dashboard$/)
})
