import { expect, test } from '@playwright/test'

const actor = process.env.PLAYWRIGHT_INCENTIVE_ACTOR
test.skip(!actor, 'Requires isolated Incentive fixture')

for (const width of [1440, 1024, 390]) test('Rule-based Incentive at ' + width + 'px', async ({ page }) => {
  await page.setViewportSize({ width, height: 900 })
  await page.goto('/login')
  await page.getByRole('textbox', { name: 'Email' }).fill(actor!)
  await page.getByLabel('Password').fill('incentive check password')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page.getByRole('button', { name: 'Log out', exact: true })).toBeVisible()
  await page.goto('/finance')
  await page.getByRole('button', { name: 'Incentives' }).click()
  await expect(page.getByRole('heading', { name: 'Incentive Rules' })).toBeVisible()
  const ruleName = 'Browser Incentive ' + width + ' ' + Date.now()
  const metric = 'Verified Cases ' + width
  await page.getByRole('textbox', { name: 'Rule Name' }).fill(ruleName)
  await page.getByRole('textbox', { name: 'Rule Metric' }).fill(metric)
  await page.getByRole('spinbutton', { name: 'Rule Target' }).fill('10')
  await page.getByRole('spinbutton', { name: 'Rule Amount' }).fill('300')
  await page.getByRole('button', { name: 'Add Incentive Rule' }).click()
  await expect(page.getByRole('listitem').filter({ hasText: ruleName })).toBeVisible()
  await page.getByRole('combobox', { name: 'Incentive Rule' }).click()
  await page.getByRole('option', { name: ruleName }).click()
  await page.getByRole('combobox', { name: 'User', exact: true }).click()
  await page.getByRole('option', { name: 'Incentive Actor' }).click()
  await page.getByRole('textbox', { name: 'Period (YYYY-MM or YYYY-Q1)' }).fill('2026-Q3')
  await page.getByRole('spinbutton', { name: 'Achievement' }).fill('8')
  await page.getByRole('button', { name: 'Save Incentive' }).click()
  await expect(page.getByText(metric, { exact: true })).toBeVisible()
  const record = page.locator('.amafh-section').filter({ hasText: metric }).last()
  await record.getByRole('button', { name: 'Delete' }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Delete' }).click()
  await expect(page.getByText(metric, { exact: true })).toHaveCount(0)
  const rule = page.getByRole('listitem').filter({ hasText: ruleName })
  await rule.getByRole('button', { name: 'Delete Rule' }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Delete' }).click()
  await expect(page.getByRole('listitem').filter({ hasText: ruleName })).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1)).toBe(false)
})
