import { expect, test, type Page } from '@playwright/test'
import { signIn } from './helpers/auth'

async function choose(page: Page, field: string, option: string) { await page.getByRole('combobox', { name: field, exact: true }).click(); await page.getByRole('option', { name: option, exact: true }).click() }
async function noOverflow(page: Page) { expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1)).toBe(false) }

for (const width of [1440, 1024, 390]) {
  test(`organization hierarchy, CRUD and filters at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    await signIn(page)
    await page.goto('/administration/organization')
    await expect(page.getByRole('heading', { name: 'Organization hierarchy' })).toBeVisible()
    await expect(page.locator('.amafh-organization-tree')).toContainText('Organization A')
    await expect(page.locator('.amafh-organization-tree')).toContainText('Business Unit A')
    await noOverflow(page)
    await page.getByRole('navigation', { name: 'Organization views' }).getByRole('button', { name: 'Teams' }).click()
    const table = page.getByRole('table', { name: 'Teams' })
    await expect(table).toBeVisible()
    await page.getByRole('searchbox', { name: 'Search' }).fill('Team C')
    await expect(table.getByRole('row', { name: /Team C/ })).toBeVisible()
    await page.getByRole('searchbox', { name: 'Search' }).fill('nothing matches')
    await expect(page.getByText('No results')).toBeVisible()
    await page.getByRole('searchbox', { name: 'Search' }).fill('')
    await page.getByRole('combobox', { name: 'Status' }).selectOption('inactive')
    await expect(table.getByRole('row', { name: /Team C/ })).toBeVisible()
    await expect(table.getByRole('row', { name: /Team A/ })).toHaveCount(0)
    await page.getByRole('combobox', { name: 'Status' }).selectOption('all')
    await page.getByRole('button', { name: 'Create Team' }).click()
    await noOverflow(page)
    await page.locator('form.amafh-organization-form').getByRole('button', { name: 'Create Team' }).click()
    await expect(page.getByText('Name is required.')).toBeVisible()
    await page.getByRole('textbox', { name: 'Name' }).fill(' team   a ')
    await page.getByRole('textbox', { name: 'Description' }).fill('Local structure test.')
    await choose(page, 'Parent', 'Department A · Department')
    await page.locator('form.amafh-organization-form').getByRole('button', { name: 'Create Team' }).click()
    await expect(page.getByText('A sibling with this name already exists.')).toBeVisible()
    await page.getByRole('textbox', { name: 'Name' }).fill('Team D')
    await page.locator('form.amafh-organization-form').getByRole('button', { name: 'Create Team' }).click()
    await expect(page.getByRole('heading', { level: 1, name: 'Team detail' })).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Team D', exact: true })).toBeVisible()
    await noOverflow(page)
    await page.reload()
    await expect(page.getByRole('heading', { name: 'Team D', exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Edit Team' }).click()
    await page.getByRole('textbox', { name: 'Name' }).fill('Team D Revised')
    await choose(page, 'Status', 'Inactive')
    await page.getByRole('button', { name: 'Save changes' }).click()
    await expect(page.getByRole('heading', { name: 'Team D Revised', exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Delete Team' }).click()
    const dialog = page.getByRole('dialog', { name: 'Delete Team' })
    await expect(dialog).toContainText('Delete Team D Revised?')
    await dialog.getByRole('button', { name: 'Cancel' }).click()
    await expect(dialog).not.toBeVisible()
    await page.getByRole('button', { name: 'Delete Team' }).click()
    await dialog.getByRole('button', { name: 'Delete', exact: true }).click()
    await expect(page).toHaveURL(/\/administration\/organization\/teams$/)
    await page.reload()
    await page.getByRole('searchbox', { name: 'Search' }).fill('Team D Revised')
    await expect(page.getByText('No results')).toBeVisible()
    await noOverflow(page)
  })
}

test('dependent records block deletion before and at repository boundary', async ({ page }) => {
  await signIn(page)
  await page.goto('/administration/organization/departments/department-1')
  await expect(page.getByRole('heading', { name: 'Department A', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Delete Department' }).click()
  const dialog = page.getByRole('dialog', { name: 'Delete Department' })
  await expect(dialog).toContainText('1 related record depends on it')
  await expect(dialog.getByRole('button', { name: 'Delete', exact: true })).toBeDisabled()
  await dialog.getByRole('button', { name: 'Cancel' }).click()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Department A', exact: true })).toBeVisible()
})

test('empty and recoverable local organization states', async ({ page }) => {
  await signIn(page)
  await page.goto('/administration/organization/teams')
  await page.evaluate(() => localStorage.setItem('amafh-v2.mock-organization.v1', JSON.stringify({ version: 1, records: [] })))
  await page.reload()
  await expect(page.getByText('Nothing here yet')).toBeVisible()
  await page.evaluate(() => localStorage.setItem('amafh-v2.mock-organization.v1', '{broken'))
  await page.reload()
  await expect(page.getByText('Could not load records')).toBeVisible()
  await page.evaluate(() => localStorage.setItem('amafh-v2.mock-organization.v1', JSON.stringify({ version: 1, records: [] })))
  await page.getByRole('button', { name: 'Try again' }).click()
  await expect(page.getByText('Nothing here yet')).toBeVisible()
})

test('nested organization routes remain protected', async ({ page }) => {
  await page.goto('/administration/organization/teams/new')
  await expect(page).toHaveURL(/\/login\?returnTo=%2Fadministration%2Forganization%2Fteams%2Fnew$/)
  await page.getByRole('textbox', { name: 'Email' }).fill('preview@example.test')
  await page.getByLabel('Password').fill('preview')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page).toHaveURL(/\/administration\/organization\/teams\/new$/)
  await expect(page.getByRole('heading', { level: 1, name: 'Create Team' })).toBeVisible()
})
