import { expect, test, type Page } from '@playwright/test'
import { signIn } from './helpers/auth'

async function choose(page: Page, field: string, option: string) {
  await page.getByRole('combobox', { name: field, exact: true }).click()
  await page.getByRole('option', { name: option, exact: true }).click()
}
async function noOverflow(page: Page) { expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1)).toBe(false) }

for (const width of [1440, 1024, 390]) {
  test(`permission search, filter, create, edit and detail at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    await signIn(page)
    await page.goto('/administration/permissions')
    const table = page.getByRole('table', { name: 'Permissions' })
    await expect(table).toBeVisible()
    await noOverflow(page)
    await page.getByRole('searchbox', { name: 'Search' }).fill('Audit Log')
    await expect(table.getByRole('row', { name: /Audit Log/ })).toBeVisible()
    await page.getByRole('searchbox', { name: 'Search' }).fill('no matching right')
    await expect(page.getByText('No results')).toBeVisible()
    await page.getByRole('searchbox', { name: 'Search' }).fill('')
    await choose(page, 'State', 'Enabled')
    await expect(table.getByRole('row', { name: /Audit Log/ })).toHaveCount(0)
    await choose(page, 'State', 'All states')
    await page.getByRole('button', { name: 'Create Permission' }).click()
    await expect(page.getByRole('heading', { level: 1, name: 'Create Permission' })).toBeVisible()
    await noOverflow(page)
    await page.locator('form.amafh-permissions-form').getByRole('button', { name: 'Create Permission' }).click()
    await expect(page.getByText('Select a valid domain.')).toBeVisible()
    await choose(page, 'Domain', 'Users')
    await choose(page, 'Action', 'View')
    await page.getByRole('textbox', { name: 'Description' }).fill('Duplicate view right.')
    await page.locator('form.amafh-permissions-form').getByRole('button', { name: 'Create Permission' }).click()
    await expect(page.getByText('This permission definition already exists.')).toBeVisible()
    await choose(page, 'Action', 'Edit')
    await page.getByRole('switch', { name: 'Enabled' }).check()
    await page.locator('form.amafh-permissions-form').getByRole('button', { name: 'Create Permission' }).click()
    await expect(page.getByText('Assign at least one User Type before enabling.')).toBeVisible()
    await page.getByRole('checkbox', { name: /User Type A/ }).check()
    await page.locator('form.amafh-permissions-form').getByRole('button', { name: 'Create Permission' }).click()
    await expect(page.getByRole('heading', { level: 1, name: 'Permission detail' })).toBeVisible()
    await expect(page.getByText('Duplicate view right.')).toBeVisible()
    await noOverflow(page)
    await page.reload()
    await expect(page.getByText('Duplicate view right.')).toBeVisible()
    await page.getByRole('button', { name: 'Edit Permission' }).click()
    await page.getByRole('textbox', { name: 'Description' }).fill('Updated edit right.')
    await page.getByRole('switch', { name: 'Enabled' }).uncheck()
    await page.getByRole('button', { name: 'Save changes' }).click()
    await expect(page.getByText('Updated edit right.')).toBeVisible()
    await expect(page.getByText('Disabled', { exact: true }).first()).toBeVisible()
    await noOverflow(page)
  })
}

test('permission empty and recoverable error states', async ({ page }) => {
  await signIn(page)
  await page.goto('/administration/permissions')
  await page.evaluate(() => localStorage.setItem('amafh-v2.mock-permissions.v1', JSON.stringify({ version: 1, permissions: [] })))
  await page.reload()
  await expect(page.getByText('Nothing here yet')).toBeVisible()
  await page.evaluate(() => localStorage.setItem('amafh-v2.mock-permissions.v1', '{broken'))
  await page.reload()
  await expect(page.getByText('Could not load records')).toBeVisible()
  await page.evaluate(() => localStorage.setItem('amafh-v2.mock-permissions.v1', JSON.stringify({ version: 1, permissions: [] })))
  await page.getByRole('button', { name: 'Try again' }).click()
  await expect(page.getByText('Nothing here yet')).toBeVisible()
})

test('nested Permission routes are protected', async ({ page }) => {
  await page.goto('/administration/permissions/new')
  await expect(page).toHaveURL(/\/login\?returnTo=%2Fadministration%2Fpermissions%2Fnew$/)
  await page.getByRole('textbox', { name: 'Email' }).fill('preview@example.test')
  await page.getByLabel('Password').fill('preview')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page).toHaveURL(/\/administration\/permissions\/new$/)
  await expect(page.getByRole('heading', { level: 1, name: 'Create Permission' })).toBeVisible()
})
