import { expect, test } from '@playwright/test'

const manager = process.env.PLAYWRIGHT_TASK_MANAGER
test.skip(!manager, 'Requires isolated Task API fixture')

for (const width of [1440, 1024, 390]) test('Task CRUD and due views at ' + width + 'px', async ({ page }) => {
  await page.setViewportSize({ width, height: 900 })
  await page.goto('/login')
  await page.getByRole('textbox', { name: 'Email' }).fill(manager!)
  await page.getByLabel('Password').fill('task flow password')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page.getByRole('button', { name: 'Log out', exact: true })).toBeVisible()
  await page.goto('/tasks')
  await expect(page.getByRole('heading', { level: 1, name: 'Tasks / Activities' })).toBeVisible()
  await page.getByRole('button', { name: 'Create Task' }).click()
  const title = 'Browser Task ' + width + ' ' + Date.now()
  await page.getByRole('textbox', { name: 'Task Title' }).fill(title)
  await page.getByRole('combobox', { name: 'Assigned To' }).click()
  await page.getByRole('option', { name: 'Task Manager' }).first().click()
  await page.getByRole('textbox', { name: 'Due Date' }).fill('2026-09-29')
  await page.getByRole('textbox', { name: 'Due Time' }).fill('12:00')
  await page.getByRole('button', { name: 'Save Task' }).click()
  await expect(page.getByRole('heading', { level: 1, name: 'Task detail' })).toBeVisible()
  await expect(page.getByRole('heading', { name: title })).toBeVisible()
  await page.getByRole('textbox', { name: 'Note' }).fill('Browser follow-up')
  await page.getByRole('button', { name: 'Add note' }).click()
  await expect(page.getByText('Browser follow-up')).toBeVisible()
  await page.getByRole('button', { name: 'Start Task' }).click()
  await expect(page.getByText('In Progress').first()).toBeVisible()
  await page.getByRole('button', { name: 'Complete', exact: true }).click()
  await expect(page.getByText('Completed').first()).toBeVisible()
  await page.getByRole('button', { name: 'Delete Task' }).click()
  await page.getByRole('button', { name: 'Delete', exact: true }).click()
  await expect(page.getByRole('heading', { level: 1, name: 'Tasks / Activities' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1)).toBe(false)
})
