import { expect, test } from '@playwright/test'

test.skip(!process.env.PLAYWRIGHT_ACCOUNT_SETUP_OWNER, 'Requires an isolated account setup owner fixture')

for (const width of [1440, 1024, 390]) test(`owner provisions an account and recipient activates it at ${width}px`, async ({ page }) => {
  await page.setViewportSize({ width, height: 900 })
  await page.goto('/login')
  await page.getByRole('textbox', { name: 'Email' }).fill(process.env.PLAYWRIGHT_ACCOUNT_SETUP_OWNER!)
  await page.getByLabel('Password').fill('account setup owner password')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page.getByRole('button', { name: 'Account security' })).toBeVisible()
  await page.getByRole('button', { name: 'Account security' }).click()
  await page.getByRole('button', { name: 'Create user account' }).click()
  await expect(page).toHaveURL(/\/account\/provision-user$/)
  const email = `browser-provision-${width}-${Date.now()}@example.test`
  await page.getByRole('textbox', { name: 'Full name' }).fill('Browser Provision Recipient')
  await page.getByRole('textbox', { name: 'Email' }).fill(email)
  await page.getByLabel('User Type').click()
  await page.getByRole('option', { name: /Provision Recipient/ }).first().click()
  await page.getByRole('button', { name: 'Create account and setup link' }).click()
  await expect(page.getByText('Account created. Share this link with the user.')).toBeVisible()
  const link = await page.getByRole('textbox', { name: 'One-time setup link' }).inputValue()
  expect(link).toContain('/set-password?token=')
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1)).toBe(false)
  await page.getByRole('button', { name: 'Log out', exact: true }).click()
  await page.goto(link)
  await page.getByRole('textbox', { name: 'New password' }).fill('browser recipient password')
  await page.getByRole('textbox', { name: 'Confirm password' }).fill('browser recipient password')
  await page.getByRole('button', { name: 'Save password' }).click()
  await expect(page.getByText('Your password is ready.')).toBeVisible()
  await page.getByRole('button', { name: 'Sign in' }).click()
  await page.getByRole('textbox', { name: 'Email' }).fill(email)
  await page.getByLabel('Password').fill('browser recipient password')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page.getByRole('button', { name: 'Log out', exact: true })).toBeVisible()
})
